name: Setup Node Environment
description: Reusable action to setup node.js environment

runs:
  using: "composite"
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
          node-version: 18

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
