name: Deploy to Netlify
description: Reusable action to deploy to Netlify and return the deploy URL

inputs:
  auth_token:
    required: true
    description: Netlify auth token
  site_id:
    required: true
    description: Netlify site ID
  dist_dir:
    required: true
    description: Path to the build output directory

outputs:
  deploy_url:
    description: The deployed Netlify URL
    value: ${{ steps.deploy.outputs.deploy_url }}

runs:
  using: "composite"
  steps:
    - name: Install Netlify CLI
      shell: bash
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      shell: bash
      id: deploy
      run: |
        export DEPLOY_URL=$(netlify deploy --prod --dir=${{ inputs.dist_dir }} \
          --site ${{ inputs.site_id }} \
          --auth ${{ inputs.auth_token }} \
          --json | jq -r '.deploy_url')
        echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
