name: Development Pipeline
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  lint-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn type-check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint-typecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Unit tests
        run: yarn unit

  deploy:
      name: Deploy
      needs: unit-tests
      runs-on: ubuntu-latest
      outputs:
        preview-url: ${{ steps.deploy.outputs.deployment-url }}

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Deploy to vercel
        id: deploy
        uses: ./.github/actions/deploy/
        with:
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          branch: ${{ github.ref_name }}

  integration-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup/

      - name: Run integration tests
        run: |
          echo "Running tests against ${{ needs.deploy.outputs.preview-url }}"
          yarn cy:run --url=${{ needs.deploy.outputs.preview-url }}

# integration-tests:
  #   name: Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: build-deploy

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup environment
  #       uses: ./.github/actions/setup/

  #     - name: Run integration tests
  #       env:
  #         BASE_URL: ${{ needs.build-deploy.outputs.deploy-url }}
  #       run: yarn test:integration
