name: Unit Tests
description: Running unit tests

on: [pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn unit
